### ISSUE TITLE
Switching out weapon attachments will save the weapon with default attachments

### ISSUE THREAD

**Issue by aaronstatic** [Arkensor/EnfusionPersistenceFramework#18]
Switching out a weapon attachment (optics/suppressors etc) then saving will save the weapon as the default prefab with the default attachment.

It's most apparent with the RHS addon as they have a very modular attachment system (GUID 595F2BF2F44836FB)

Repro steps:

1. Load the RHS addon (right click addon in workbench launcher and "Open with addon(s)") https://reforger.armaplatform.com/workshop/595F2BF2F44836FB-RHS-StatusQuo
2. Add a weapon to your test world that has attachment/s (ie https://enfusionengine.com/api/redirect?to=enfusion://ResourceManager/~RHSStatusQuo:Prefabs/Weapons/Rifles/AK74M/Rifle_AK74M_1P78.et)
3. Add a different attachment you can use to switch it out (ie https://enfusionengine.com/api/redirect?to=enfusion://ResourceManager/~RHSStatusQuo:Prefabs/Weapons/Attachments/Optics/1p87/Optic_1P87_new.et)
4. Start world, pick up weapon, pick up attachment, switch them out
5. Save and reload

The weapon will load with the default attachment in the prefab, not the one that it was switched out with

**Comment by Arkensor** [comment]
Confirmed fixed probably due to update of the RHS mod and them using the correct base prefabs that EPF can hook.
