### ISSUE TITLE
NPC Prefabs placed on the map will spawn with outfits on the ground (client-side)

### ISSUE THREAD

**Issue by JeanLaigri** [Arkensor/EnfusionPersistenceFramework#31]
How to reproduce:
- Create a basic scenario
- Add EPF and EDF to the scenario
- Use PeerTool
- Place {E9D854B8D5D74129}anims/anm/Tutorial/Character_Blank_Tutorial.et

You can notice that the server will see the NPC wearing the outfits while the client(s) will see it naked (outfits on the ground)
Disable EPF component and the issue is gone

**Comment by Tomboru** [comment]
Not a bug, you forgot to add an "RplComponent" to your NPC.
Without it it drops the items on the ground.

(I don't think it needs any fix, but @Arkensor you have to decide)

**Comment by goodmittens** [comment]
![image](https://github.com/user-attachments/assets/68451758-f19b-45f7-9789-94a9ea78b8d6)
![image](https://github.com/user-attachments/assets/ab47d855-f4f6-4f5f-bde4-be99831a2a9c)
Is the RPL Comp shown above configured correctly? (Second image is a client connected to server, it does not show the bug in reforger tools)
