### ISSUE TITLE
incorrect info in guideline

### ISSUE THREAD

**Issue by kOepi123** [Arkensor/EnfusionPersistenceFramework#41]
In the below image it says to add both components to the basegame.
However these with these names there are only two other components similar, but not exactly with these names.
Either I am doing something wrong, or the instructions are inaccurate.

![image](https://github.com/Arkensor/EnfusionPersistenceFramework/assets/11195228/d11bb91b-3206-4f9d-8ad4-6a1b0cd26988)

**Comment by Arkensor** [comment]
~~You need to add them, they are not added by default~~
Fixed the docs.
